/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque.index'
import { Route as AuthenticatedComprasIndexRouteImport } from './routes/_authenticated/compras.index'
import { Route as AuthenticatedEstoqueRetiradaRouteImport } from './routes/_authenticated/estoque.retirada'
import { Route as AuthenticatedEstoqueRequisicoesRouteImport } from './routes/_authenticated/estoque.requisicoes'
import { Route as AuthenticatedEstoqueRelatorioRouteImport } from './routes/_authenticated/estoque.relatorio'
import { Route as AuthenticatedEstoqueProdutosRouteImport } from './routes/_authenticated/estoque.produtos'
import { Route as AuthenticatedEstoquePorcionarRouteImport } from './routes/_authenticated/estoque.porcionar'
import { Route as AuthenticatedEstoqueLocaisRouteImport } from './routes/_authenticated/estoque.locais'
import { Route as AuthenticatedEstoqueImportarRouteImport } from './routes/_authenticated/estoque.importar'
import { Route as AuthenticatedEstoqueEntradaRouteImport } from './routes/_authenticated/estoque.entrada'
import { Route as AuthenticatedEstoqueContagemRouteImport } from './routes/_authenticated/estoque.contagem'
import { Route as AuthenticatedEstoqueCategoriasRouteImport } from './routes/_authenticated/estoque.categorias'
import { Route as AuthenticatedComprasPedidoRouteImport } from './routes/_authenticated/compras.pedido'
import { Route as AuthenticatedComprasListaRouteImport } from './routes/_authenticated/compras.lista'
import { Route as AuthenticatedComprasHistoricoRouteImport } from './routes/_authenticated/compras.historico'
import { Route as AuthenticatedChecklistTipoRouteImport } from './routes/_authenticated/checklist.$tipo'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminRequisicoesCompraRouteImport } from './routes/_authenticated/admin/requisicoes-compra'
import { Route as AuthenticatedAdminFornecedoresRouteImport } from './routes/_authenticated/admin/fornecedores'
import { Route as AuthenticatedAdminChecklistsRouteImport } from './routes/_authenticated/admin/checklists'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedComprasIndexRoute =
  AuthenticatedComprasIndexRouteImport.update({
    id: '/compras/',
    path: '/compras/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueRetiradaRoute =
  AuthenticatedEstoqueRetiradaRouteImport.update({
    id: '/retirada',
    path: '/retirada',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueRequisicoesRoute =
  AuthenticatedEstoqueRequisicoesRouteImport.update({
    id: '/requisicoes',
    path: '/requisicoes',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueRelatorioRoute =
  AuthenticatedEstoqueRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueProdutosRoute =
  AuthenticatedEstoqueProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoquePorcionarRoute =
  AuthenticatedEstoquePorcionarRouteImport.update({
    id: '/porcionar',
    path: '/porcionar',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueLocaisRoute =
  AuthenticatedEstoqueLocaisRouteImport.update({
    id: '/locais',
    path: '/locais',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueImportarRoute =
  AuthenticatedEstoqueImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueEntradaRoute =
  AuthenticatedEstoqueEntradaRouteImport.update({
    id: '/entrada',
    path: '/entrada',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueContagemRoute =
  AuthenticatedEstoqueContagemRouteImport.update({
    id: '/contagem',
    path: '/contagem',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueCategoriasRoute =
  AuthenticatedEstoqueCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedComprasPedidoRoute =
  AuthenticatedComprasPedidoRouteImport.update({
    id: '/compras/pedido',
    path: '/compras/pedido',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComprasListaRoute =
  AuthenticatedComprasListaRouteImport.update({
    id: '/compras/lista',
    path: '/compras/lista',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComprasHistoricoRoute =
  AuthenticatedComprasHistoricoRouteImport.update({
    id: '/compras/historico',
    path: '/compras/historico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChecklistTipoRoute =
  AuthenticatedChecklistTipoRouteImport.update({
    id: '/checklist/$tipo',
    path: '/checklist/$tipo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRequisicoesCompraRoute =
  AuthenticatedAdminRequisicoesCompraRouteImport.update({
    id: '/admin/requisicoes-compra',
    path: '/admin/requisicoes-compra',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFornecedoresRoute =
  AuthenticatedAdminFornecedoresRouteImport.update({
    id: '/admin/fornecedores',
    path: '/admin/fornecedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminChecklistsRoute =
  AuthenticatedAdminChecklistsRouteImport.update({
    id: '/admin/checklists',
    path: '/admin/checklists',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/admin/requisicoes-compra': typeof AuthenticatedAdminRequisicoesCompraRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/checklist/$tipo': typeof AuthenticatedChecklistTipoRoute
  '/compras/historico': typeof AuthenticatedComprasHistoricoRoute
  '/compras/lista': typeof AuthenticatedComprasListaRoute
  '/compras/pedido': typeof AuthenticatedComprasPedidoRoute
  '/estoque/categorias': typeof AuthenticatedEstoqueCategoriasRoute
  '/estoque/contagem': typeof AuthenticatedEstoqueContagemRoute
  '/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/estoque/importar': typeof AuthenticatedEstoqueImportarRoute
  '/estoque/locais': typeof AuthenticatedEstoqueLocaisRoute
  '/estoque/porcionar': typeof AuthenticatedEstoquePorcionarRoute
  '/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/estoque/relatorio': typeof AuthenticatedEstoqueRelatorioRoute
  '/estoque/requisicoes': typeof AuthenticatedEstoqueRequisicoesRoute
  '/estoque/retirada': typeof AuthenticatedEstoqueRetiradaRoute
  '/compras/': typeof AuthenticatedComprasIndexRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/admin/requisicoes-compra': typeof AuthenticatedAdminRequisicoesCompraRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/checklist/$tipo': typeof AuthenticatedChecklistTipoRoute
  '/compras/historico': typeof AuthenticatedComprasHistoricoRoute
  '/compras/lista': typeof AuthenticatedComprasListaRoute
  '/compras/pedido': typeof AuthenticatedComprasPedidoRoute
  '/estoque/categorias': typeof AuthenticatedEstoqueCategoriasRoute
  '/estoque/contagem': typeof AuthenticatedEstoqueContagemRoute
  '/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/estoque/importar': typeof AuthenticatedEstoqueImportarRoute
  '/estoque/locais': typeof AuthenticatedEstoqueLocaisRoute
  '/estoque/porcionar': typeof AuthenticatedEstoquePorcionarRoute
  '/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/estoque/relatorio': typeof AuthenticatedEstoqueRelatorioRoute
  '/estoque/requisicoes': typeof AuthenticatedEstoqueRequisicoesRoute
  '/estoque/retirada': typeof AuthenticatedEstoqueRetiradaRoute
  '/compras': typeof AuthenticatedComprasIndexRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/checklists': typeof AuthenticatedAdminChecklistsRoute
  '/_authenticated/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/_authenticated/admin/requisicoes-compra': typeof AuthenticatedAdminRequisicoesCompraRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/checklist/$tipo': typeof AuthenticatedChecklistTipoRoute
  '/_authenticated/compras/historico': typeof AuthenticatedComprasHistoricoRoute
  '/_authenticated/compras/lista': typeof AuthenticatedComprasListaRoute
  '/_authenticated/compras/pedido': typeof AuthenticatedComprasPedidoRoute
  '/_authenticated/estoque/categorias': typeof AuthenticatedEstoqueCategoriasRoute
  '/_authenticated/estoque/contagem': typeof AuthenticatedEstoqueContagemRoute
  '/_authenticated/estoque/entrada': typeof AuthenticatedEstoqueEntradaRoute
  '/_authenticated/estoque/importar': typeof AuthenticatedEstoqueImportarRoute
  '/_authenticated/estoque/locais': typeof AuthenticatedEstoqueLocaisRoute
  '/_authenticated/estoque/porcionar': typeof AuthenticatedEstoquePorcionarRoute
  '/_authenticated/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/_authenticated/estoque/relatorio': typeof AuthenticatedEstoqueRelatorioRoute
  '/_authenticated/estoque/requisicoes': typeof AuthenticatedEstoqueRequisicoesRoute
  '/_authenticated/estoque/retirada': typeof AuthenticatedEstoqueRetiradaRoute
  '/_authenticated/compras/': typeof AuthenticatedComprasIndexRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/estoque'
    | '/perfil'
    | '/admin/checklists'
    | '/admin/fornecedores'
    | '/admin/requisicoes-compra'
    | '/admin/usuarios'
    | '/checklist/$tipo'
    | '/compras/historico'
    | '/compras/lista'
    | '/compras/pedido'
    | '/estoque/categorias'
    | '/estoque/contagem'
    | '/estoque/entrada'
    | '/estoque/importar'
    | '/estoque/locais'
    | '/estoque/porcionar'
    | '/estoque/produtos'
    | '/estoque/relatorio'
    | '/estoque/requisicoes'
    | '/estoque/retirada'
    | '/compras/'
    | '/estoque/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/perfil'
    | '/admin/checklists'
    | '/admin/fornecedores'
    | '/admin/requisicoes-compra'
    | '/admin/usuarios'
    | '/checklist/$tipo'
    | '/compras/historico'
    | '/compras/lista'
    | '/compras/pedido'
    | '/estoque/categorias'
    | '/estoque/contagem'
    | '/estoque/entrada'
    | '/estoque/importar'
    | '/estoque/locais'
    | '/estoque/porcionar'
    | '/estoque/produtos'
    | '/estoque/relatorio'
    | '/estoque/requisicoes'
    | '/estoque/retirada'
    | '/compras'
    | '/estoque'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/checklists'
    | '/_authenticated/admin/fornecedores'
    | '/_authenticated/admin/requisicoes-compra'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/checklist/$tipo'
    | '/_authenticated/compras/historico'
    | '/_authenticated/compras/lista'
    | '/_authenticated/compras/pedido'
    | '/_authenticated/estoque/categorias'
    | '/_authenticated/estoque/contagem'
    | '/_authenticated/estoque/entrada'
    | '/_authenticated/estoque/importar'
    | '/_authenticated/estoque/locais'
    | '/_authenticated/estoque/porcionar'
    | '/_authenticated/estoque/produtos'
    | '/_authenticated/estoque/relatorio'
    | '/_authenticated/estoque/requisicoes'
    | '/_authenticated/estoque/retirada'
    | '/_authenticated/compras/'
    | '/_authenticated/estoque/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/compras/': {
      id: '/_authenticated/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof AuthenticatedComprasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/retirada': {
      id: '/_authenticated/estoque/retirada'
      path: '/retirada'
      fullPath: '/estoque/retirada'
      preLoaderRoute: typeof AuthenticatedEstoqueRetiradaRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/requisicoes': {
      id: '/_authenticated/estoque/requisicoes'
      path: '/requisicoes'
      fullPath: '/estoque/requisicoes'
      preLoaderRoute: typeof AuthenticatedEstoqueRequisicoesRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/relatorio': {
      id: '/_authenticated/estoque/relatorio'
      path: '/relatorio'
      fullPath: '/estoque/relatorio'
      preLoaderRoute: typeof AuthenticatedEstoqueRelatorioRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/produtos': {
      id: '/_authenticated/estoque/produtos'
      path: '/produtos'
      fullPath: '/estoque/produtos'
      preLoaderRoute: typeof AuthenticatedEstoqueProdutosRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/porcionar': {
      id: '/_authenticated/estoque/porcionar'
      path: '/porcionar'
      fullPath: '/estoque/porcionar'
      preLoaderRoute: typeof AuthenticatedEstoquePorcionarRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/locais': {
      id: '/_authenticated/estoque/locais'
      path: '/locais'
      fullPath: '/estoque/locais'
      preLoaderRoute: typeof AuthenticatedEstoqueLocaisRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/importar': {
      id: '/_authenticated/estoque/importar'
      path: '/importar'
      fullPath: '/estoque/importar'
      preLoaderRoute: typeof AuthenticatedEstoqueImportarRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/entrada': {
      id: '/_authenticated/estoque/entrada'
      path: '/entrada'
      fullPath: '/estoque/entrada'
      preLoaderRoute: typeof AuthenticatedEstoqueEntradaRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/contagem': {
      id: '/_authenticated/estoque/contagem'
      path: '/contagem'
      fullPath: '/estoque/contagem'
      preLoaderRoute: typeof AuthenticatedEstoqueContagemRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/categorias': {
      id: '/_authenticated/estoque/categorias'
      path: '/categorias'
      fullPath: '/estoque/categorias'
      preLoaderRoute: typeof AuthenticatedEstoqueCategoriasRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/compras/pedido': {
      id: '/_authenticated/compras/pedido'
      path: '/compras/pedido'
      fullPath: '/compras/pedido'
      preLoaderRoute: typeof AuthenticatedComprasPedidoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compras/lista': {
      id: '/_authenticated/compras/lista'
      path: '/compras/lista'
      fullPath: '/compras/lista'
      preLoaderRoute: typeof AuthenticatedComprasListaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compras/historico': {
      id: '/_authenticated/compras/historico'
      path: '/compras/historico'
      fullPath: '/compras/historico'
      preLoaderRoute: typeof AuthenticatedComprasHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checklist/$tipo': {
      id: '/_authenticated/checklist/$tipo'
      path: '/checklist/$tipo'
      fullPath: '/checklist/$tipo'
      preLoaderRoute: typeof AuthenticatedChecklistTipoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/requisicoes-compra': {
      id: '/_authenticated/admin/requisicoes-compra'
      path: '/admin/requisicoes-compra'
      fullPath: '/admin/requisicoes-compra'
      preLoaderRoute: typeof AuthenticatedAdminRequisicoesCompraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/fornecedores': {
      id: '/_authenticated/admin/fornecedores'
      path: '/admin/fornecedores'
      fullPath: '/admin/fornecedores'
      preLoaderRoute: typeof AuthenticatedAdminFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/checklists': {
      id: '/_authenticated/admin/checklists'
      path: '/admin/checklists'
      fullPath: '/admin/checklists'
      preLoaderRoute: typeof AuthenticatedAdminChecklistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedEstoqueRouteChildren {
  AuthenticatedEstoqueCategoriasRoute: typeof AuthenticatedEstoqueCategoriasRoute
  AuthenticatedEstoqueContagemRoute: typeof AuthenticatedEstoqueContagemRoute
  AuthenticatedEstoqueEntradaRoute: typeof AuthenticatedEstoqueEntradaRoute
  AuthenticatedEstoqueImportarRoute: typeof AuthenticatedEstoqueImportarRoute
  AuthenticatedEstoqueLocaisRoute: typeof AuthenticatedEstoqueLocaisRoute
  AuthenticatedEstoquePorcionarRoute: typeof AuthenticatedEstoquePorcionarRoute
  AuthenticatedEstoqueProdutosRoute: typeof AuthenticatedEstoqueProdutosRoute
  AuthenticatedEstoqueRelatorioRoute: typeof AuthenticatedEstoqueRelatorioRoute
  AuthenticatedEstoqueRequisicoesRoute: typeof AuthenticatedEstoqueRequisicoesRoute
  AuthenticatedEstoqueRetiradaRoute: typeof AuthenticatedEstoqueRetiradaRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
}

const AuthenticatedEstoqueRouteChildren: AuthenticatedEstoqueRouteChildren = {
  AuthenticatedEstoqueCategoriasRoute: AuthenticatedEstoqueCategoriasRoute,
  AuthenticatedEstoqueContagemRoute: AuthenticatedEstoqueContagemRoute,
  AuthenticatedEstoqueEntradaRoute: AuthenticatedEstoqueEntradaRoute,
  AuthenticatedEstoqueImportarRoute: AuthenticatedEstoqueImportarRoute,
  AuthenticatedEstoqueLocaisRoute: AuthenticatedEstoqueLocaisRoute,
  AuthenticatedEstoquePorcionarRoute: AuthenticatedEstoquePorcionarRoute,
  AuthenticatedEstoqueProdutosRoute: AuthenticatedEstoqueProdutosRoute,
  AuthenticatedEstoqueRelatorioRoute: AuthenticatedEstoqueRelatorioRoute,
  AuthenticatedEstoqueRequisicoesRoute: AuthenticatedEstoqueRequisicoesRoute,
  AuthenticatedEstoqueRetiradaRoute: AuthenticatedEstoqueRetiradaRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
}

const AuthenticatedEstoqueRouteWithChildren =
  AuthenticatedEstoqueRoute._addFileChildren(AuthenticatedEstoqueRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAdminChecklistsRoute: typeof AuthenticatedAdminChecklistsRoute
  AuthenticatedAdminFornecedoresRoute: typeof AuthenticatedAdminFornecedoresRoute
  AuthenticatedAdminRequisicoesCompraRoute: typeof AuthenticatedAdminRequisicoesCompraRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedChecklistTipoRoute: typeof AuthenticatedChecklistTipoRoute
  AuthenticatedComprasHistoricoRoute: typeof AuthenticatedComprasHistoricoRoute
  AuthenticatedComprasListaRoute: typeof AuthenticatedComprasListaRoute
  AuthenticatedComprasPedidoRoute: typeof AuthenticatedComprasPedidoRoute
  AuthenticatedComprasIndexRoute: typeof AuthenticatedComprasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAdminChecklistsRoute: AuthenticatedAdminChecklistsRoute,
  AuthenticatedAdminFornecedoresRoute: AuthenticatedAdminFornecedoresRoute,
  AuthenticatedAdminRequisicoesCompraRoute:
    AuthenticatedAdminRequisicoesCompraRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedChecklistTipoRoute: AuthenticatedChecklistTipoRoute,
  AuthenticatedComprasHistoricoRoute: AuthenticatedComprasHistoricoRoute,
  AuthenticatedComprasListaRoute: AuthenticatedComprasListaRoute,
  AuthenticatedComprasPedidoRoute: AuthenticatedComprasPedidoRoute,
  AuthenticatedComprasIndexRoute: AuthenticatedComprasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
