// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Projeto Supabase "Matrix" (dmqfprakaepphcubqbka).
// Fixado direto (sem variáveis de ambiente) para garantir que o app use o banco Matrix.
// A chave publishable é pública por design — pode ficar no código do cliente.
const SUPABASE_URL = "https://dmqfprakaepphcubqbka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_q_NvRr7f3bzVLKVX6vjQBw_6-LbavhV";

function createSupabaseClient() {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
